# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            "Teng Rui's Blog"
tagline:          "powered by Jekyll"
description:      "Teng Rui's blog using Jekyll Metro theme"
url:              'http://tengrui.cc'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url: /archive/

# Author Details
author:         "Teng Rui"
linkedin:       "https://www.linkedin.com/pub/rui-teng/"
twitter:        "https://twitter.com/Rui_Teng"
facebook:       "https://www.facebook.com/tengrui.cc"
gplus:          "https://plus.google.com/111799168211135203870/"

# Google Analytics
# gahandler: ' '

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.9
