# Site settings
title: Teng Rui's Jekyll Blog
email: tengrui@live.cn
description: > # this means to ignore newlines until "baseurl:"
  Teng Rui's Jekyll Blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tengrui.cc" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  tengrui

# Build settings
markdown: kramdown
